README.md, package-lock.json, package.json, src/Commands/GenerateArchive.ts, src/Commands/RunScan.ts, src/Parsers/MockRequestsParser.ts, src/Parsers/RequestCrawler.ts
* implement aka pool workers
* handle big nexmock files
* other minors
=> fix: disable ssl verification and improve parsers

.github/workflows/config.yml, .npmignore, README.md, commitlint.config.js, package-lock.json, package.json, release.config.js, src/Commands/RunScan.ts, src/Strategy/ScanManager.ts
=> #21 feat/remove type and protocol options

src/Commands/RunScan.ts, src/Strategy/ScanManager.ts
=> feat(scan): add the ability to select tests to run

src/Strategy/ScanManager.ts
=> feat(scan): add missing tests

.github/workflows/auto-build.yml, .github/workflows/deploy.yml, .github/workflows/release.yml, src/Strategy/ScanManager.ts
=> Fix #33/stop command finishes with 404 error

README.md, package-lock.json, package.json, src/Commands/PollingScanStatus.ts, src/Strategy/Failure/Polling.ts
=> feat(polling): add ability to set a timeout for polling

README.md, src/Commands/RunScan.ts, src/Strategy/ScanManager.ts
=> feat(run): add ability to set agent ids

src/Strategy/ScanManager.ts
=> feat(scan): add support of "open_database" and "html_injection" tests

src/Strategy/ScanManager.ts
=> feat(scan): add support of "open_buckets" test

src/Config/CliBuilder.ts
=> fix(builder): decorating errors, params and helps

Dockerfile, README.md, src/Commands/RunAgent.ts
=> feat(agent): rework command to accept env variables

src/Bus/Brokers/RabbitMQBus.ts, src/Bus/Brokers/RabbitMQErrorHandler.ts
=> fix(bus): better error handling on disconnect

README.md, src/Commands/UploadArchive.ts
=> fix(archive): spec type casting

src/Bus/Brokers/RabbitMQBus.ts, src/Commands/RunAgent.ts
=> feat(bus): support both unicast and multicast

src/Bus/Brokers/RabbitBackoff.ts, src/Bus/Brokers/RabbitMQBus.ts
=> fix(bus): re-connect on trusted error

src/Bus/Brokers/RabbitMQBus.ts, src/Commands/RunRepeater.ts
=> perf(bus): set no-ack mode

README.md
=> docs(readme): fix quick start

.github/workflows/auto-build.yml, .github/workflows/release.yml, .gitignore, .releaserc, package-lock.json, package.json
=> build: create a single executable out

src/Utils/Helpers.ts
=> fix(utils): use the reducer to build objects from entries

src/Archive/Validators/HarValidator.ts, src/Archive/Validators/NexMockValidator.ts, src/Config/DefaultConfigReader.ts, tools/msi/product.wxs
=> fix(config): loading commonjs modules

src/RequestExecutor/DefaultRequestExecutor.ts, src/Utils/Helpers.ts
=> fix(executor): escape characters in url

src/Bus/Brokers/RabbitMQBus.ts, src/index.ts
=> fix: increase thread pool size

src/Bus/Brokers/RabbitMQBus.ts, src/Utils/Logger.ts
=> refactor(bus): ensure the message is delivered

src/Bus/Brokers/RabbitMQBus.ts, src/Utils/Helpers.ts
=> fix(bus): fallback on decoding uri

src/Commands/RunRepeater.ts, src/RequestExecutor/DefaultRequestExecutor.ts
=> fix(executor): prevent following redirect

src/RequestExecutor/DefaultRequestExecutor.ts
https://tools.ietf.org/html/rfc7230#section-3.2.6
closes #96
=> fix(executor): bypass check for invalid field-vchar

src/Scan/Breakpoint.ts
=> fix(breakpoint): null pointer exception

src/Commands/RunScan.ts, src/Scan/Scans.ts
=> feat(scan): add support of new tests

public/src/app/components/main/main.component.ts, public/src/app/models/CustomValidators.ts, public/src/app/models/index.ts, src/Commands/RunRepeater.ts, src/Wizard/Endpoints/SetTokensEndpoint.ts, src/Wizard/Models/Credentials.ts
=> feat(repeater): replace `--remove` with `--remove-daemon`

src/Utils/Helpers.ts
=> fix: invalid exec args

src/Archive/RestArchives.ts
=> fix(archive): uploading files

.github/workflows/deploy.yml, src/Commands/RunRepeater.ts
=> feat(repeater): allow to configure request timeouts

src/Archive/Parsers/NexMock/DefaultHarRecorder.ts, src/RequestExecutor/DefaultRequestExecutor.ts, src/Wizard/Connectivity/HTTPConnectivity.ts
=> fix(wizard): skip server certificate verification

.github/workflows/deploy.yml, src/Scripts/VirtualScript.ts
=> fix(scripts): remove zero width space characters

src/Wizard/Platform/Readline/ReadlinePlatform.ts
=> refactor(configure): improve wording

src/Bus/Brokers/RabbitMQBus.ts, src/Commands/Integration.ts, src/Handlers/Events/RegisterIssue.ts, src/Handlers/Events/RequestProjects.ts, src/Handlers/RegisterIssueHandler.ts, src/Handlers/RequestProjectsHandler.ts, src/Integrations/IntegrationClient.ts, src/Integrations/JiraIntegrationClient.ts, src/Integrations/Project.ts
=> fix(integration): minor improvements and adjustments

docker-compose.yaml, package-lock.json, package.json, rabbit/enabled_plugins, rabbit/rabbitmq.conf, src/Bus/Brokers/RabbitBackoff.ts, src/Commands/Integration.ts, src/Commands/RunRepeater.ts
=> Fix #147/bus permissions

README.md
=> docs(readme): update links to KB

src/RequestExecutor/HttpRequestExecutor.ts
=> fix(executor): wrong serialization when a script is used

src/Archive/Archives.ts, src/Archive/Parsers/BaseParser.ts, src/Archive/Parsers/Parser.ts, src/Archive/RestArchives.ts, src/Commands/UploadArchive.ts
=> fix(archive): postman/swagger file uploading

src/Commands/Integration.ts, src/Handlers/Events/ExecuteScript.ts, src/Handlers/SendRequestHandler.ts, src/Integrations/IntegrationType.ts, src/RequestExecutor/Request.ts, src/RequestExecutor/WsRequestExecutor.ts
=> feat(executor): add correlation_id to WS requests

src/Utils/Helpers.ts, src/Wizard/Connectivity/AMQConnectivity.ts, src/Wizard/Connectivity/HTTPConnectivity.ts, src/Wizard/Connectivity/TCPConnectivity.ts, src/Wizard/Platform/Readline/ReadlinePlatform.ts
=> fix(configure): run connectivity tests concurrently

src/Wizard/Platform/Readline/ReadlinePlatform.ts
=> fix(configure): typo in the network testing wizard

src/Commands/RunScan.ts, src/Scan/Scans.ts
=> feat(scan): add auth object for run scans command

.github/workflows/deploy.yml, .gitignore, package-lock.json, package.json, src/Commands/RunRepeater.ts, src/Config/container.ts, src/RequestExecutor/Certificates.ts, src/RequestExecutor/CertificatesLoader.ts, src/RequestExecutor/HttpRequestExecutor.ts, src/RequestExecutor/Request.ts, src/RequestExecutor/WsRequestExecutor.ts, src/RequestExecutor/index.ts, tools/msi/product.wxs, typings/win-ca/index.d.ts, win-ca.d.ts
=> feat(repeater): add user cert

src/RequestExecutor/HttpRequestExecutor.ts
=> fix(executor): add support for Node 10 while headers updating

src/Commands/RunRepeater.ts, src/RequestExecutor/HttpRequestExecutor.ts, src/RequestExecutor/Request.ts, src/RequestExecutor/WsRequestExecutor.ts, src/Utils/Helpers.ts
=> feat(executor): add option to specify PFX or PKCS12 passphrase

src/Commands/RunRepeater.ts, src/Utils/Helpers.ts
=> feat(repeater): use JSON option to specify certificates

src/RequestExecutor/Request.ts, src/Utils/Helpers.ts
=> fix(request): use WHATWG URL to encode unicode characters

Dockerfile, src/Bus/Brokers/RabbitMQBus.ts, src/Scan/RestScans.ts, src/Scan/Scans.ts
=> fix(scan): adopt new headers structure

src/RequestExecutor/HttpRequestExecutor.ts
=> fix(executor): condition to truncate a body

src/Commands/RunRepeater.ts
=> fix(repeater): extend whitelist of content types

src/RequestExecutor/HttpRequestExecutor.ts
=> fix(executor): fallback to text/plain while parsing content-type

package-lock.json, package.json, src/Config/CliBuilder.ts, src/index.ts
=> fix(cli): refuse using yargonaut

src/Bus/Brokers/RabbitMQBus.ts, src/Commands/Integration.ts, src/Commands/PollingScanStatus.ts, src/Commands/RetestScan.ts, src/Commands/RunScan.ts, src/Commands/StopScan.ts, src/Commands/UploadArchive.ts, src/Config/CliBuilder.ts, src/Integrations/IntegrationOptions.ts, src/Integrations/JiraIntegrationClient.ts
=> refactor(*): make `--insecure` as global option

src/Wizard/Connectivity/HTTPConnectivity.ts, src/Wizard/Connectivity/TCPConnectivity.ts
=> fix(wizard): connectivity testers

.github/workflows/deploy.yml
We run out of storage because of docker images
=> Don't store docker images in GitHub repo

src/Bus/Brokers/RabbitMQBus.ts, src/Config/CliInfo.ts, webpack.config.js
=> fix(*): set CLI version via environment plugin

.github/workflows/deploy.yml
=> fix(*): pass the version of CLI to env

src/Commands/RunRepeater.ts, src/Handlers/Events/RepeaterRegistering.ts, src/Repeater/DefaultRepeaterLauncher.ts
=> feat(repeater): ignore remote scripts if local scripts are used

src/Repeater/DefaultRepeaterLauncher.ts
=> fix(repeater): prevent sending disconnected status on error

src/Handlers/Events/RepeaterRegistered.ts, src/Repeater/DefaultRepeaterLauncher.ts
=> fix(repeater): prevent running multiple repeater with the same id

src/RequestExecutor/CertificatesLoader.ts
=> fix(executor): add the link to KB

src/Commands/UploadArchive.ts
=> fix(archive): invalid values argument type

src/Handlers/Events/RepeaterRegistered.ts, src/Repeater/DefaultRepeaterLauncher.ts
=> fix(repeater): invalid version on run

README.md, src/Commands/RunRepeater.ts, src/Handlers/Events/RepeaterRegistered.ts, src/Repeater/DefaultRepeaterLauncher.ts, src/Utils/Helpers.ts
=> fix: add validation of --id

src/Commands/RunRepeater.ts, src/Commands/RunScan.ts, src/Scan/RestScans.ts, src/Scan/Scans.ts
BREAKING CHANGE: CI integrations have no longer supported
close #237
=> feat(scan)!: allow setting ticket integrations

src/Commands/RunScan.ts
=> fix(scan): split integration argument on first instance of separator

src/Commands/RunRepeater.ts, src/RequestExecutor/HttpRequestExecutor.ts
=> feat(repeater): add support for reuse connection

.github/workflows/deploy.yml, .mocharc.js, package-lock.json, package.json, src/Commands/Integration.ts, src/Handlers/NetworkTestHandler.ts, src/Repeater/DefaultRepeaterLauncher.ts, src/Utils/Helpers.ts
=> fix: add support for `PKG_EXECPATH` when pkg is used

src/Scan/Scans.ts
=> feat(scan): add support for XML/XPath Injection test

src/Commands/RunRepeater.ts, src/RequestExecutor/HttpRequestExecutor.ts
=> fix(repeater): make proxy related arguments working

src/Bus/Proxy/Proxy.ts
=> fix(repeater): proper setup of proxy credentials

.github/workflows/auto-build.yml, .github/workflows/deploy.yml, .github/workflows/release.yml
=> fix: use the same version of Node.js to compile binaries

src/Bus/Proxy/Proxy.ts
=> fix(bus): fallback to host if socks proto does not imply DNS lookup

src/Archive/Archives.ts, src/Commands/UploadArchive.ts
=> fix(archive): uploading specification files

src/Scan/Scans.ts
=> feat(scan): add support for Common Server Misconfiguration

src/Scan/Scans.ts
=> revert: add support for Common Server Misconfiguration

src/Commands/RunRepeater.ts, src/RequestExecutor/HttpRequestExecutor.spec.ts, src/RequestExecutor/HttpRequestExecutor.ts, src/RequestExecutor/WsRequestExecutor.spec.ts
=> fix(repeater): add `x-javascript` to whitelisted mimes

src/Scan/RestScans.ts
=> feat(scan): send creation info alongside a scan config

LICENSE, README.md, src/Bus/Brokers/RabbitMQBus.ts, src/Commands/Integration.ts, src/Commands/PollingScanStatus.ts, src/Commands/RetestScan.ts, src/Commands/RunRepeater.ts, src/Commands/RunScan.ts, src/Commands/StopScan.ts, src/Commands/UploadArchive.ts, src/Config/CliBuilder.ts, src/Repeater/DefaultRepeaterLauncher.ts, src/RequestExecutor/CertificatesLoader.ts, src/Wizard/Readline/ReadlinePlatform.ts, tools/msi/LICENSE.rtf, tools/msi/product.wxs
=> docs: replace domain in links for documentation

src/Scripts/DefaultVirtualScrips.spec.ts, src/Scripts/FSScriptLoader.spec.ts, src/Scripts/VirtualScript.spec.ts
=> test(scripts): cover by unit tests

src/Commands/RunScan.ts, src/Scan/Scans.ts
=> feat(scan): allow setting exclusions via CLI options

src/Commands/RunRepeater.ts
=> fix(repeater): ignore `REPEATER` environment variable

src/RequestExecutor/HttpRequestExecutor.spec.ts, src/RequestExecutor/HttpRequestExecutor.ts
=> fix(repeater): decode response body before truncating

src/Bus/Brokers/RabbitMQBus.ts
=> fix(bus): re-connect when socket closed abruptly during opening handshake

.github/workflows/auto-build.yml, .github/workflows/deploy.yml, .github/workflows/release.yml, .releaserc, package-lock.json, package.json
=> fix: build using legacy C++ standard library

src/Commands/RunScan.ts, src/Scan/RestScans.ts, src/Scan/Scans.ts
=> feat(scan)!: get rid of `integration` option

Dockerfile, README.md, package.json, src/Commands/Configure.ts, src/Config/CliBuilder.ts, src/Utils/Helpers.spec.ts, src/Utils/Helpers.ts
=> fix: replace neuralegion domain with brightsec

src/Scan/RestScans.spec.ts, src/Scan/RestScans.ts
=> fix(scan): clarify the endpoint used to retrieve a file info

src/Scan/Scans.ts
=> feat(scan): add graphql_introspection to test_type enum

src/Scan/BreakpointType.ts, src/Scan/DefaultBreakpointFactory.ts, src/Scan/Scans.ts
=> feat(polling): add `Critical` severity breakpoint

src/Scan/Scans.ts
=> feat(scan): add `Lack of Resource and Rate Limiting` test

src/RequestExecutor/CertificatesLoader.ts
=> fix(docs): update `--cacerts` option docs link

src/RequestExecutor/Request.spec.ts, src/RequestExecutor/Request.ts, src/Utils/Helpers.spec.ts
=> feat(request): add host with wildcard support to --cert=json option value

src/Scan/Scans.ts
=> feat(scan): add amazon-s3-takeover test type

src/Scan/Scans.ts
=> feat(scan): add `cve_test` test type

src/Commands/RunScan.ts, src/Scan/Scans.ts
=> fix(scan): align Scan tests config with other clients

tools/scripts/install.cmd, tools/scripts/install.sh
=> build: improve installation scripts

src/RequestExecutor/HttpRequestExecutor.spec.ts, src/RequestExecutor/HttpRequestExecutor.ts, src/RequestExecutor/Request.spec.ts, src/RequestExecutor/Request.ts
=> fix(executor): preserve path traversal vulnerability

src/RequestExecutor/Request.spec.ts, src/RequestExecutor/Request.ts
=> fix(executor): setting the request headers

src/Commands/RunScan.ts, src/Scan/Scans.ts
A bucket is a group of tests that either target application areas (e.g BE = Server side & API, FE = Client side) or share a common testing focus (e.g business logic, signature-based (CVE tests), harmful tests) that can be picked as a whole.
closes #399
=> feat(scan): introduce test buckets

src/Scan/Scans.ts
=> feat(scan): add `stored_xss` and deprecate `dom_xss`

src/Commands/RunScan.ts
=> fix(scan): respect tests/buckets params mutually exclusiveness 

src/Scan/Scans.ts
=> feat(scan): add new `prompt_injection` test type

src/Scan/Scans.ts
=> feat(scan): add new `css_injection` test type

src/index.ts
=> fix(repeater): override the max HTTP header size

src/Scan/Scans.ts
=> feat(scan): add new `iframe_injection` test type

src/Repeater/ServerRepeaterLauncher.ts
=> fix(repeater): remove repeater id from startup log

src/Scan/Scans.ts
=> revert: add new `css_injection` test type

package-lock.json, package.json
=> fix: erroneous use of `+` before service name

src/Repeater/DefaultRepeaterServer.ts
=> fix(repeater): use appropriate event to manage scripts

.github/workflows/deploy.yml, Dockerfile, package-lock.json, package.json, src/Config/container.ts, src/Handlers/Events/RepeaterRegistering.ts, src/Repeater/DefaultRepeaterLauncher.ts, src/Repeater/DefaultRuntimeDetector.ts, src/Repeater/RepeaterServer.ts, src/Repeater/RuntimeDetector.ts, src/Repeater/ServerRepeaterLauncher.ts, src/Repeater/index.ts
=> feat(repeater): send runtime information upon repeater registration

src/Config/CliInfo.ts, src/Repeater/DefaultRuntimeDetector.ts
=> fix(*): extract distribution from parsed package.json

package-lock.json, package.json, src/Handlers/Events/RepeaterRegistering.ts, src/Repeater/DefaultRepeaterLauncher.ts, src/Repeater/DefaultRuntimeDetector.ts, src/Repeater/RepeaterServer.ts, src/Repeater/RuntimeDetector.ts, src/Repeater/ServerRepeaterLauncher.ts
=> feat(repeater): collect ci information

.github/workflows/e2e.yml
=> test: add tests for MSI

.github/workflows/e2e.yml
=> test: fix tests for executables

src/Repeater/DefaultRepeaterServer.ts, src/Repeater/RepeaterServer.ts, src/Repeater/ServerRepeaterLauncher.ts
=> fix(repeater): deploy repeater on every connection

.github/workflows/e2e.yml
=> ci(e2e): add production environment

.github/workflows/e2e.yml
=> ci(e2e): put environment into run name

src/Repeater/DefaultRepeaterServer.ts, src/Repeater/RepeaterServer.ts, src/Repeater/ServerRepeaterLauncher.ts
=> fix(repeater): alert when update is available

src/Commands/RunScan.ts, src/Scan/RestScans.ts, src/Scan/Scans.ts
=> fix(scan) ignore default params if template provided

src/Scan/Scans.ts
=> feat(scan): add "Broken Object Level Authorization" scan test

src/Repeater/ServerRepeaterLauncher.ts
=> fix(repeater): show repeater started message after first deploy

src/Commands/RunRepeater.ts, src/Config/CliBuilder.ts, src/Repeater/DefaultRepeaterLauncher.ts, src/Repeater/DefaultRepeaterServer.ts, src/Repeater/ServerRepeaterLauncher.ts, src/Utils/Logger.ts
=> refactor: capture only specific errors

src/Config/CliBuilder.ts, src/Utils/Sentry.ts, src/Utils/index.ts
=> refactor: remove `Sentry` util

src/Utils/Logger.ts
=> fix(logger): remove unused imports

src/Scan/Scans.ts
=> feat(scan): add `google_cloud_storage` and `azure_blob_storage` tests

src/Archive/Validators/HarValidator.ts, src/RequestExecutor/Request.ts
For details please refer to https://node.green/
=> fix: align Node.js and ECMAScript versions

.github/workflows/composite/npm/action.yml
=> test(polling): fix flaky tests

src/RequestExecutor/HttpRequestExecutor.spec.ts, src/RequestExecutor/HttpRequestExecutor.ts, src/RequestExecutor/Request.ts
=> perf(repeater): add option to bypass decompression

src/Repeater/DefaultRepeaterServer.ts
=> fix(repeater): set `rejectUnauthorized` using `insecure` switch

src/Config/CliBuilder.ts, src/Repeater/DefaultRepeaterServer.ts, src/Repeater/RepeaterServer.ts, src/Repeater/ServerRepeaterLauncher.ts
* Improve connection handling by refining event listeners and error handling
* Refine repeater event types and interfaces for better type safety and clarity
relates-to: #515
=> fix(repeater): enhance repeater lifecycle management

src/Utils/Helpers.ts
=> fix: properly handle both `--cluster` and `--hostname` options

src/RequestExecutor/HttpRequestExecutor.ts
=> fix(repeater): decode base64 bodies before scripts

package-lock.json, package.json
bump the yargs version to 17 to be able to use async builders
relates-to: #493
=> build(deps): bump yargs from 16.2.0 to 17.7.2

src/Commands/RunScan.ts, src/Scan/RestScans.ts, src/Scan/Scans.ts
Leverage the API to run default tests when user didn't provide any
closes #493
=> feat(scan): remove hardcoded test types

src/Commands/GetEntryPoints.spec.ts, src/EntryPoint/RestEntryPoints.spec.ts
cover `entrypoint:list` command with tests
=> test(entrypoints): improve test coverage

src/Commands/GetEntryPoints.spec.ts, src/Commands/GetEntryPoints.ts
Allow to pretty print the list of entrypoints if the flag `--pretty` passed
=> feat(entrypoints): add pretty print option

src/Config/CliBuilder.ts, src/Scan/BasePolling.ts, src/Scan/PollingFactory.ts, src/Utils/Helpers.spec.ts, src/Utils/Helpers.ts
Make the global `--timeout` flag to accept duration string. e.g. 10s, 1m, 1h, 1m, 1d
=> feat(*): make timeout flag accept duration strings

src/Repeater/ServerRepeaterLauncher.ts
=> fix(repeater): print out started log event after deploy

src/Commands/RunRepeater.ts, src/Config/CliBuilder.ts
PROXY is an alias to --proxy flag
NO_PROXY is an alias to --proxy-domains-bypass flag
=> feat(repeater): add PROXY and NO_PROXY env variables

package-lock.json, package.json
asset paths were pointing to a wrong non existing files. This change fixes the issue.
=> fix: correct native prebuilt add-on paths

src/Utils/ErrorMessageFactory.ts
=> feat: descriptive api errors

src/Scan/RestScans.ts, src/Scan/Scans.ts
=> feat(scan): replace deprecated attack parameter locations in RestScans configuration

src/Commands/EntryPointsUpdateHost.spec.ts, src/Commands/EntryPointsUpdateHost.ts, src/Commands/PollingHostUpdateJobStatus.spec.ts, src/Commands/PollingHostUpdateJobStatus.ts, src/EntryPoint/DefaultHostUpdateJobStatusPollingFactory.ts, src/EntryPoint/EntryPoints.ts, src/EntryPoint/HostUpdateJobStatusPolling.spec.ts, src/EntryPoint/HostUpdateJobStatusPolling.ts, src/EntryPoint/HostUpdateJobStatusPollingFactory.ts, src/EntryPoint/RestEntryPoints.ts, src/container.ts, src/index.ts
=> feat(entrypoints): add host update job status polling and bulk host update commands

.github/workflows/deploy.yml
=> chore(ci): move npm token to bitwarden

src/Repeater/DefaultRepeaterServer.ts
=> feat(repeater): allow reconnection for network disruption errors

.github/workflows/deploy.yml, .github/workflows/e2e.yml
upgrading windows os version to 2022 as Windows-2019 has been deprecated https://github.com/actions/runner-images/issues/12045
=> chore(ci): upgrade windows 2019 to 2022

src/index.ts
this commit will be removed later
=> fix(*): just to test the next release
