.gitignore
package.json
src/Handlers/Events/NetworkTest.ts
src/Handlers/NetworkTestHandler.ts

feat(configure): rework `NetworkTest` to execute traceroute remotely

---

src/RequestExecutor/WsRequestExecutor.ts

fix(request-executor): `unhandledRejection` when `WsRequestExecutor` cannot connect to target

---

src/RequestExecutor/WsRequestExecutor.spec.ts
src/RequestExecutor/WsRequestExecutor.ts

fix(request-executor): handshake timeout in `WsRequestExecutor`

---

.github/workflows/deploy.yml
Dockerfile
LICENSE
README.md
package-lock.json
package.json
src/Commands/Configure.ts
src/Commands/Integration.ts
src/Commands/VersionCommand.ts
src/Config/CliBuilder.ts
src/Config/CliInfo.ts
src/Config/DefaultConfigReader.ts
src/Repeater/DefaultRepeaterLauncher.ts
src/Scan/Breakpoints/OnAny.ts
src/Scan/Breakpoints/OnSeverity.ts
src/Utils/Helpers.spec.ts
src/Utils/Helpers.ts
src/Wizard/FSTokens.ts
tests/Commands/version.spec.ts
tools/msi/LICENSE.rtf
tools/msi/build.ps1
tools/msi/product.wxs

BREAKING CHANGE:
* The command-line interface previously known as `nexploit-cli` is no longer supported. It has been renamed to `bright-cli`:
**Before**
```bash
$ nexploit-cli -h
```
**After**
```bash
$ bright-cli -h
```
* The `--nogui` option for the `configure` command is no longer supported:
**Before**
```bash
$ nexploit-cli configure --nogui
```
**After**
```bash
$ bright-cli configure
```
* The `--api` and `--bus` options have been removed, use the `--cluster` option instead:
**Before**
```bash
$ nexploit-cli repeater --bus amqps://amq.app.brightsec.com:5672
```
**After**
```bash
$ bright-cli repeater --cluster app.brightsec.com
```
closes #378

feat: rename project into `bright-cli`

---

.github/workflows/deploy.yml

Ubuntu 18 is no longer supported starting from the April. Please refer to the article for the details: https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
relates-to: actions/runner-images#7388

ci: add a container job to the matrix

---

src/RequestExecutor/HttpRequestExecutor.spec.ts
src/RequestExecutor/HttpRequestExecutor.ts
src/Utils/NormalizeZlibDeflateTransformStream.spec.ts
src/Utils/NormalizeZlibDeflateTransformStream.ts

feat(request-executor): support `deflate` encoding without `zlib` headers

---

src/Commands/RunRepeater.ts
src/Config/container.ts
src/Repeater/DefaultRepeaterLauncher.ts

feat(repeater): preserve legacy rabbitmq flow

---

.github/workflows/deploy.yml

`npm pkg` is not available until npm 7.20

fix(*): use `npx json` to set distribution type

---

src/Config/CliInfo.ts
src/Config/container.ts

fix(*): load package data relatively to module dir

---

src/Commands/RunRepeater.ts

feat(repeater): rename `legacy` option to `rabbitmq`

---

src/Utils/Logger.ts

Some errors are logged in `printf`-like format, so despite we send all logged arguments to Sentry, the captured message is too generic. At the same time some passed logged arguments are being filtered by Sentry, which makes issue investigation harder.
This commit solves this problem by utilizing `utils.format` function.
relates-to: #458

refactor(sentry): capture formatted messages

---

src/Commands/RunScan.ts

fix(scan): use tests from `run:scan` args

---

src/Repeater/DefaultRepeaterServer.ts

fix(repeater): reconnect on low-level connection errors

---

package-lock.json
package.json

Prevents potential issues caused by automatic updates to these dependencies

fix(deps): pin dependencies using `node-gyp-build`

---

src/Commands/GenerateArchive.ts
src/Commands/Integration.ts
src/Commands/RunRepeater.ts
src/Commands/UploadArchive.ts
src/Config/CliBuilder.ts
src/RequestExecutor/CertificatesLoader.ts

Deprecated several commands and options for cleanup and simplification:
Commands:
- `archive:generate`: Deprecated in favor of `archive:upload`, which supports HAR, OAS, or Postman collections. NexMock is no longer supported.
Options:
Common:
- `--cluster`: Deprecated. Use `--hostname` instead.
For the `repeater` command:
- `--rabbitmq`: Deprecated with no direct replacement.
- `--headers`: Deprecated. Use `--header` instead.
For the `archive:upload` command:
- `--variables`: Deprecated. Embed variables directly into the file. For current best practices on handling variables, see https://learning.postman.com/docs/sending-requests/variables/variables/#variable-scopes
- `--headers`: Deprecated in the context of `archive:upload`. Use `--header` when running a scan using the `scan:run` …

docs: deprecated some commands and options

---

src/Commands/GetEntryPoints.ts
src/Commands/index.ts
src/Config/container.ts
src/EntryPoint/EntryPoints.ts
src/EntryPoint/RestEntryPoints.ts
src/EntryPoint/index.ts
src/index.ts

Add `entrypoints:list` command to get all entrypoints of project:
```bash
bright-cli entrypoints:list --project <project-id>
```
**Output**:
A list of all entry points for the specified project.
**Benefits**:
- Streamlines the process of retrieving project entry points directly from the CLI.
- Enhances integration with CI/CD pipelines.
- Aligns bright-cli capabilities with our existing API features.
**Example**:
```bash
$ bright-cli entrypoints:list --token <api-key> --project <project-id>
[ { "id": "s7vJhe2nmwJZXr1dpxbUmg", "url": "https://brightsec.com" } ]
```

feat(entrypoints): add command to list entrypoints

---

src/Commands/Configure.ts
src/Commands/RunRepeater.ts
src/Commands/UploadArchive.ts
src/Config/index.ts
src/Scan/RestScans.spec.ts
src/container.ts
src/index.ts

having this file in config folder causing errors:
```
bright-cli % node -r ts-node/register/transpile-only -r tsconfig-paths/register src/index.ts scan:run --token abc --name abc
[2024-07-01T16:45:24.503Z] [ERROR  ] - Error during "scan:run": TypeInfo not known for "undefined"
```

fix(*): resolve circular dependency in DI

---

.github/workflows/deploy.yml

Bypasses unsupported node versions check
Node 16 is required to build linux binaries compatible with old distros (see #449)
relates-to: actions/checkout#1809

fix: allow node 16 in actions to build linux binary

---

.github/workflows/deploy.yml

CentOS 7 reached EOL on June 30, 2024 which also marked EOL for mirrorlist.centos.org

fix: replace broken CentOS package mirrors

---

.github/workflows/deploy.yml

Fixes builds as macOS 11 runners are removed

fix: use macOS 12 to build binary

---

Dockerfile

running traceroute requires root access as it creates raw sockets.
Since we use non-root user in Docker image, we need to allow the
node to create raw sockets and listen of ICMP error packets.
for that use the setcap command which comes in libcap package:
setcap 'cap_net_raw+ep' $(which node)

fix(repeater): add cap_net_raw+ep capabilities for node in Docker image

---

package-lock.json
package.json

Bumps the deps: [ws](https://github.com/websockets/ws) and [braces](https://github.com/micromatch/braces).
Updates `ws` from 8.1.0 to 8.17.1
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/websockets/ws/releases">ws's releases</a>.</em></p>
<blockquote>
<h2>8.17.1</h2>
<h1>Bug fixes</h1>
<ul>
<li>Fixed a DoS vulnerability (<a href="https://redirect.github.com/websockets/ws/issues/2231">#2231</a>).</li>
</ul>
<p>A request with a number of headers exceeding the[<code>server.maxHeadersCount</code>][]
threshold could be used to crash a ws server.</p>
<pre lang="js"><code>const http = require('http');
const WebSocket = require('ws');
<p>const wss = new WebSocket.Server({ port: 0 }, function () {
const chars = …

build(deps): bump ws from 8.1.0 to 8.18.0

---

src/Scan/RestScans.ts

the `applyDefaultSettings` was doing null check a little wrong and as a result the default param were always applied.

fix(scan): correct param handling to respect user provided values

---

src/Commands/RunScan.ts
src/Scan/Scans.ts

Users can pass a list of entrypoint IDs to run the scan on specific entrypoints.
For Example:
```
bright-cli scan:run --entrypoint <entrypoint_id1> <entrypoint_id2> <entrypoint_id3> ...
```
If a project is specified and the `--entrypoint` flag is added without specifying entrypoint IDs, the scan will run on the first 2000 project-level entrypoints.
For example:
```
bright-cli scan:run --project <PROJECT_ID> --entrypoint
```

feat(scan): run scan with project level entrypoints

---

src/Commands/GetEntryPoints.ts
src/Commands/PollingScanStatus.ts
src/Commands/RetestScan.ts
src/Commands/RunRepeater.ts
src/Commands/RunScan.ts
src/Commands/StopScan.ts
src/Commands/UploadArchive.ts
src/Config/CliBuilder.ts
src/EntryPoint/RestEntryPoints.ts
src/Repeater/DefaultRepeaterServer.ts
src/RequestExecutor/HttpRequestExecutor.ts
src/RequestExecutor/RequestExecutorOptions.ts
src/Scan/RestScans.ts

- Rename “proxy-internal” to “proxy-target”.
- Rename “proxy-external” to “proxy-bright”. 
- Add a new “proxy-domains” flag as an optional flag. It can be accepted when the user is setting either “proxy-target” or “proxy”. It can receive a comma-separated list of domains which will be proxied. Any domain that is not part of the list won’t be proxied. Notes: Support for wildcard is required. If I specify “*.foo.bar” as one of the domains, “a.foo.bar”, “b.foo.bar”, etc. will all be proxied.
- Bright domains will always be proxied when using with the “proxy” flag, without a need to have them explicitly listed as part of the “proxy-domains” list. if the user doesn’t want to proxy bright domains, he should use only "proxy-target"

feat(proxy): add --proxy-domains flag for domain-specific proxying with wildcard support

---

src/Repeater/DefaultRepeaterServer.ts

Ping historically was there to signal over RMQ that repeater is still connected
Socket.IO implementation has built in mechanism for disconnection detection https://socket.io/docs/v4/engine-io-protocol/#heartbeat

refactor(repeater): stop sending ping event

---

src/Commands/RunRepeater.ts
src/Repeater/DefaultRepeaterServer.ts
src/Repeater/RepeaterServer.ts
src/Repeater/ServerRepeaterLauncher.ts
src/RequestExecutor/HttpRequestExecutor.spec.ts
src/RequestExecutor/HttpRequestExecutor.ts
src/RequestExecutor/RequestExecutorOptions.ts

Introduce a maxBodySize limit to manage large response bodies, truncating or omitting them as necessary to prevent socket connection disruptions

fix(repeater): introduce max-body-size to avoid breaking socket connection on large responses

---

src/Commands/GetEntryPoints.spec.ts
src/Commands/GetEntryPoints.ts
src/Commands/RunScan.spec.ts
src/EntryPoint/EntryPoints.ts
src/EntryPoint/RestEntryPoints.spec.ts
src/EntryPoint/RestEntryPoints.ts

use --connectivity or --status flags to filter out entrypoints

feat(entrypoints): filter entrypoints by connectivity and status

---

.github/workflows/e2e.yml

e2e pipeline fails on Ubuntu 16.04 and 18.04 due to the recent default switch to node20 in actions/checkout. Node20 requires GLIBC 2.28 or higher, which these environments lack. To resolve this, we’re setting the `ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true` environment variable to allow fallback to a compatible Node version, restoring pipeline stability.
Useful links:
* [GitHub changelog: node20 default](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/)
* [GitHub issue #1809](https://github.com/actions/checkout/issues/1809)

ci: fix node20 compatibility issues in e2e pipeline

---

.github/workflows/e2e.yml

`macos-11` runner has been [deprecated and removed](https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/) from the list of available hosted runners in GitHub

ci: use macos-12 for e2e tests

---

package-lock.json
package.json

Together with #609, enables updating Node.js to the latest LTS version (v22) to support the full range of runtimes, as specified in the public docs (the last 3 LTS)

build(deps): bump os-service from 1.2.2 to 1.2.6

---

package-lock.json
package.json

Together with #608, enables updating Node.js to the latest LTS version (v22) to support the full range of runtimes, as specified in the public docs (the last 3 LTS)

build(deps): bump raw-socket from 1.8.2 to 1.8.6

---

src/Utils/Logger.ts

BREAKING CHANGE: Warning logs are now written to `stderr` instead of `stdout`.

feat(*): write to stderr for errors and warnings

---

.github/workflows/deploy.yml

Ensure the artifact is gonna be uploaded using a compatible version of `actions/upload-artifact` with `actions/download-artifact`. For more information, visit the GitHub Artifacts FAQ: https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md

build(deps-dev): bump actions/download-artifact and actions/upload-artifact from 3 to 4

---

src/Commands/RunRepeater.ts
src/RequestExecutor/HttpRequestExecutor.ts
src/RequestExecutor/RequestExecutorOptions.ts

this flag allows specific requests with URLs matching any of the hosts provided in the flag’s input to bypass the proxy when it is enabled.

feat(repeater): add --proxy-domains-bypass flag

---

.github/workflows/deploy.yml

the centos/devtoolset-7-toolchain-centos7:7 has been replaced by redhat/ubi8, but install scripts were not. This change replaces the yum commands with a dnf.

chore: replace yum with dnf for redhat/ubi8

---

src/Config/SystemConfigManager.ts

It's a regular case if users do not .brightclirc file Just print regular message instead of printing stacktrace

chore: no panic if .brightclirc does not exist

---

package.json

the rotating-file-stream use ESM import system while cli app uses CommonJS. In order to be able to use rotating-file-stream we need to add it to the asset list.

fix(pkg): add rotating-file-stream to asset list

---

src/Scan/RestScans.ts
src/Scan/Scans.ts

There are 2 mistyped attack params:
* artifical-fragment
* artifical-query
But it's not accidental, because Scan API used to require exactly these mistyped params.
To improve this, we amended our API to accept amended values. In this change, we are
adding support to amended values:
```
ARTIFICAL_FRAGMENT = 'artifical-fragment', // deprecated, use ARTIFICIAL_FRAGMENT instead
ARTIFICAL_QUERY = 'artifical-query', // deprecated, use ARTIFICIAL_QUERY instead
ARTIFICIAL_FRAGMENT = 'artificial-fragment',
ARTIFICIAL_QUERY = 'artificial-query',
```
Then if users are using incorrect ones, replace them to amended ones that API requires.

refactor(scan): replace deprecated attack parameter locations in RestScans configuration

---

src/Commands/RunRepeater.ts
src/RequestExecutor/Request.spec.ts
src/RequestExecutor/Request.ts

Allow users to set multiple certificates attached to port number of host. For this users must add the `port` param to Cert object:
```
{
"path": "/path/to/certificates/client.pfx",
"hostname": "brightsec.com",
"passphrase": "password", 
"port":"8443"     <---- port number
}
```
The feature does not work unless users explicitly set port number. When no port number is specified, the logic will fallback to existing only host based checks.

feat: multiple certificates per port number of host
